server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: rigel-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@userOrIpKeyResolver}"
          routes:
            - id: bellatrix-auth
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/auth/**
            - id: betelgeuse-core
              uri: ${CORE_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/core/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
